---
all:
  children:
    fortigates:
      hosts:
        fgt-lab:
          ansible_host: 192.0.2.10
          ansible_user: "{{ lookup('env', 'FORTIGATE_USERNAME') | default('admin', true) }}"
          ansible_password: "{{ lookup('env', 'FORTIGATE_PASSWORD') }}"
          ansible_connection: httpapi
          ansible_network_os: fortinet.fortios.fortios
          ansible_httpapi_use_ssl: true
          ansible_httpapi_validate_certs: false
          ansible_httpapi_port: 443

